function Hd = muae_power_filter(Fs)
%MUAE_POWER_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 06-Dec-2022 15:07:10

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.
Fpass = 200;         % Passband Frequency
Fstop = 220;         % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 80;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
