function Hd = muae_bandpass_filter(Fs)
%MUAE_BANDPASS_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 06-Dec-2022 14:56:51

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

Fstop1 = 450;         % First Stopband Frequency
Fpass1 = 500;         % First Passband Frequency
Fpass2 = 5000;        % Second Passband Frequency
Fstop2 = 5500;        % Second Stopband Frequency
Astop1 = 60;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 80;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
